apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: open-heating
      defaultBucket: heating
    secureJsonData:
      token: open-heating-token
    isDefault: true
